name: Build Tweak
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: theos/theos
      env:
        THEOS: /opt/theos
    steps:
      - uses: actions/checkout@v4
      - name: Build Package
        run: |
          cd $GITHUB_WORKSPACE
          make clean package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1
      - uses: actions/upload-artifact@v4
        with:
          name: LSClock.deb
          path: packages/*.deb
